development:
  adapter: postgresql
  database: captureit_db
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: captureit_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: captureit_db
  pool: 5
  timeout: 5000


